// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IamUIClient is the client API for IamUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IamUIClient interface {
	// ListEngineSpecs returns a list of Identity & Access Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (IamUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type iamUIClient struct {
	cc grpc.ClientConnInterface
}

func NewIamUIClient(cc grpc.ClientConnInterface) IamUIClient {
	return &iamUIClient{cc}
}

func (c *iamUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (IamUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &IamUI_ServiceDesc.Streams[0], "/v1.IamUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &iamUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IamUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type iamUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *iamUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *iamUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.IamUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IamUIServer is the server API for IamUI service.
// All implementations must embed UnimplementedIamUIServer
// for forward compatibility
type IamUIServer interface {
	// ListEngineSpecs returns a list of Identity & Access Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, IamUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedIamUIServer()
}

// UnimplementedIamUIServer must be embedded to have forward compatible implementations.
type UnimplementedIamUIServer struct {
}

func (UnimplementedIamUIServer) ListEngineSpecs(*ListEngineSpecsRequest, IamUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedIamUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedIamUIServer) mustEmbedUnimplementedIamUIServer() {}

// UnsafeIamUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IamUIServer will
// result in compilation errors.
type UnsafeIamUIServer interface {
	mustEmbedUnimplementedIamUIServer()
}

func RegisterIamUIServer(s grpc.ServiceRegistrar, srv IamUIServer) {
	s.RegisterService(&IamUI_ServiceDesc, srv)
}

func _IamUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IamUIServer).ListEngineSpecs(m, &iamUIListEngineSpecsServer{stream})
}

type IamUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type iamUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *iamUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _IamUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.IamUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IamUI_ServiceDesc is the grpc.ServiceDesc for IamUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IamUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.IamUI",
	HandlerType: (*IamUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _IamUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _IamUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "iam-ui.proto",
}
