project_id: '491513'
api_token_env: 'CROWDIN_PERSONAL_TOKEN'
preserve_hierarchy: true
files: [
    # JSON translation files
    {
      source: '/webui/src/locales/en/data.json',
      translation: '/webui/src/locales/%two_letters_code%/data.json',
    },
  ]